
services:
  database:
    image: mysql:latest
    build:

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=www.gzhu.edu.cn
    volumes:
      - ./

  web_and_sipder:
    build:
      dockerfile: ./
    ports:
      - "5000:80"
    depends_on:
      - database
